## Part 1: Theoretical Queltionk 

1.Tensors:
The fundamental building block in TensorFlow.
Multidimensional arrays that hold numerical data (floating-point, integers) or other types like strings or booleans.
Examples:
A 2D tensor representing an image (height x width).
A 1D tensor holding a sequence of numbers.
A 3D tensor for volumetric data (e.g., 3D medical scans).

2.Variables:
Persistent data structures that store trainable parameters (weights and biases) of your model.
Values can be updated during the training process using optimizers.
TensorFlow manages the variables within the computational graph.
Examples:
Defining model weights and biases as variables.
Updating these variables based on the loss function and optimizer during training.

3.Strings: Represented by tf.string tensors for textual data.

4.Booleans: Represented by tf.bool tensors for logical values (True/False).

5.Sparse Tensors: Efficiently represent data with many zero entries, useful for recommender systems or natural language processing.

1.Constants (tf.constant):
    Represent fixed, unchangeable values.
    Once created, their values cannot be updated.
    
2.Variables (tf.Variable): 
    Represent mutable data that can be updated during program execution.
    Essential for storing and training model parameters (weights and biases) as they need to be adjusted based on the loss function.
    TensorFlow tracks variables within the computational graph for efficient optimization.

In [7]:
#constant
import tensorflow as tf
learning_rate = tf.constant(0.01)  # Fixed learning rate for training
learning_rate

<tf.Tensor: shape=(), dtype=float32, numpy=0.01>

In [8]:
#variable
import tensorflow as tf

w = tf.Variable(tf.random.normal([784, 10]))  # Weights for a model (randomly initialized)
w

<tf.Variable 'Variable:0' shape=(784, 10) dtype=float32, numpy=
array([[ 0.7991778 ,  1.1549237 ,  2.2278092 , ..., -0.87790704,
        -0.69442177, -0.6969919 ],
       [-0.44462046,  0.8245747 ,  1.058038  , ..., -0.50793993,
        -0.40612203, -0.4364217 ],
       [-0.25238517,  0.06505982,  0.07399543, ..., -0.66150343,
        -0.11843639, -0.6508913 ],
       ...,
       [ 0.43911234,  0.27463755, -0.12559731, ..., -0.04526976,
         1.0937405 , -0.19129714],
       [ 0.4942011 ,  1.0681407 , -0.12608048, ...,  0.3806356 ,
         0.9608428 ,  2.1989136 ],
       [ 1.5400738 , -0.03987854,  0.07830472, ...,  2.1695504 ,
         0.81734914, -0.6669307 ]], dtype=float32)>

1. Matrix Addition (tf.add):

Performs element-wise addition between two tensors.
Shapes must be compatible for addition (broadcasting is allowed for compatible shapes).

2. Matrix Multiplication (tf.linalg.matmul):

Performs matrix multiplication between two tensors.
Inner dimensions (columns of the first tensor and rows of the second tensor) must be equal for multiplication.
Outer dimensions can be broadcast if compatible.

3. Element-Wise Operations (tf.math.*):
    
Perform operations on corresponding elements of two tensors.
Shapes must be compatible (broadcasting is allowed).
Common element-wise operations include:
tf.math.multiply: Element-wise multiplication.
tf.math.add: Element-wise addition (same as matrix addition for compatible shapes).
tf.math.subtract: Element-wise subtraction.
tf.math.divide: Element-wise division.
Many other mathematical operations are available in tf.math.

In [10]:
#Example
    ## Matrix Addition (tf.add)##
import tensorflow as tf
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
added_matrix = tf.add(matrix_a, matrix_b)
print(added_matrix)  # Output: [[6 8] [10 12]]
     ## Matrix Multiplication (tf.linalg.matmul) ##
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
product_matrix = tf.linalg.matmul(matrix_a, matrix_b)
print(product_matrix)  # Output: [[19 22] [43 50]]
    ## Element-Wise Operations (tf.math.*) ##
matrix_a = tf.constant([[1, 2], [3, 4]])
multiplier = tf.constant(2)
element_wise_product = tf.math.multiply(matrix_a, multiplier)
print(element_wise_product)  # Output: [[2 4] [6 8]]

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)


## Part 2: Practical Implementation

Task 1: Creating and Manipulating Matricek

In [12]:
# Define the shape of the matrix (2 rows, 2 columns)
shape = (2, 2)
# Create a random normal matrix with mean 0 and standard deviation 1
A = tf.random.normal(shape)
# Print the values of matrix A
print(A.numpy())

[[-0.27307793  0.30820268]
 [ 2.287117    1.0581897 ]]


In [13]:
import tensorflow as tf

# Get the desired dimension (x) from the user
x = int(input("Enter the desired dimension (x) for the Gaussian matrix: "))
# Ensure positive dimension
if x <= 0:
  print("Error: Dimension must be a positive integer.")
else:
  # Truncate values outside 2 standard deviations from the mean (0)
  stddev = 1.0  # You can adjust this value to control the spread of the distribution
  truncation_limit = 2 * stddev
  # Create a truncated normal matrix with mean 0 and standard deviation stddev
  B = tf.random.truncated_normal((x, x), mean=0.0, stddev=stddev, seed=None, dtype=tf.float32)
  # Print the values of matrix B
  print(B.numpy())

Enter the desired dimension (x) for the Gaussian matrix:  3


[[-0.07452052 -0.645923   -0.15519139]
 [ 1.5490913   1.8410037  -0.86855227]
 [-0.12232517 -1.14241     0.15056388]]


In [14]:
import tensorflow as tf
# Define the shape of the matrix (2 rows, 2 columns)
shape = (2, 2)
# Specify the desired standard deviation (replace 0.x with your chosen value)
stddev = 0.  # We'll modify this value later
# Prompt the user for the standard deviation
user_stddev = float(input("Enter the desired standard deviation (positive number): "))
# Ensure positive standard deviation
if user_stddev <= 0:
  print("Error: Standard deviation must be a positive number.")
else:
  # Update the standard deviation with user input
  stddev = user_stddev
  # Create a random normal matrix with mean 2 and the specified standard deviation
  C = tf.random.normal(shape, mean=2.0, stddev=stddev)
  # Print the values of matrix C
  print(C.numpy())

Enter the desired standard deviation (positive number):  3


[[2.3967626  0.49727023]
 [4.6694784  2.72831   ]]


In [15]:
import tensorflow as tf
# Define the shape of the matrices (2x2)
shape = (2, 2)
# Create a random normal matrix A with mean 0 and standard deviation 1
A = tf.random.normal(shape)
# Prompt the user for the dimension (x) of the Gaussian matrix B
x = int(input("Enter the desired dimension (x) for the Gaussian matrix B: "))
# Ensure positive dimension
if x <= 0:
  print("Error: Dimension must be a positive integer.")
else:
  # Truncate values outside 2 standard deviations from the mean (0)
  stddev = 1.0  # You can adjust this value to control the spread of the distribution
  truncation_limit = 2 * stddev
  # Create a truncated normal matrix B with mean 0 and standard deviation stddev
  B = tf.random.truncated_normal((x, x), mean=0.0, stddev=stddev, seed=None, dtype=tf.float32)
  # Perform matrix addition and store the result in D
  D = tf.add(A, B[:2, :2])  # Select the top-left 2x2 submatrix of B for addition
  # Print the values of matrices A, B (2x2 submatrix), and D
  print("Matrix A:")
  print(A.numpy())
  print("\nMatrix B (top-left 2x2 submatrix):")
  print(B[:2, :2].numpy())  # Select the top-left 2x2 submatrix for printing
  print("\nMatrix D (A + B):")
  print(D.numpy())

Enter the desired dimension (x) for the Gaussian matrix B:  3


Matrix A:
[[ 1.0927862   0.160523  ]
 [-0.16880876  0.5822695 ]]

Matrix B (top-left 2x2 submatrix):
[[ 0.61943626  0.6560017 ]
 [ 1.0057894  -0.01444351]]

Matrix D (A + B):
[[1.7122225  0.8165247 ]
 [0.83698064 0.567826  ]]


In [16]:
import tensorflow as tf
# Define the shape of the matrices (2x2)
shape = (2, 2)
# Specify the desired standard deviation for matrix C (replace 0.x with your chosen value)
stddev = 0.  # We'll modify this value later
# Prompt the user for the standard deviation
user_stddev = float(input("Enter the desired standard deviation (positive number) for matrix C: "))
# Ensure positive standard deviation
if user_stddev <= 0:
  print("Error: Standard deviation must be a positive number.")
else:
  # Update the standard deviation for matrix C
  stddev = user_stddev
  # Create a random normal matrix C with mean 2 and the specified standard deviation
  C = tf.random.normal(shape, mean=2.0, stddev=stddev)
  # Perform matrix multiplication (assuming D has compatible dimensions)
  E = tf.linalg.matmul(C, D)
  # Print the values of matrices C, D, and E
  print("Matrix C:")
  print(C.numpy())
  print("\nMatrix D:")
  print(D.numpy())
  print("\nMatrix E (C * D):")
  print(E.numpy())

Enter the desired standard deviation (positive number) for matrix C:  4


Matrix C:
[[-0.901551   5.5544605]
 [ 1.3498356  3.7036514]]

Matrix D:
[[1.7122225  0.8165247 ]
 [0.83698064 0.567826  ]]

Matrix E (C * D):
[[3.10532   2.4178283]
 [5.4111032 3.2052035]]


Task 2: Performing Additional Matrix Operationk

In [17]:
import tensorflow as tf
# Define the shape of the matrix (2 rows, 2 columns)
shape = (2, 2)
# Minimum and maximum values for the uniform distribution
minval = 0.0  # You can adjust this value
maxval = 1.0  # You can adjust this value
# Create a random uniform matrix F
F = tf.random.uniform(shape, minval=minval, maxval=maxval, dtype=tf.float32)
# Print the values of matrix F
print(F.numpy())

[[0.7740722  0.759274  ]
 [0.01919842 0.01035619]]


In [18]:
G = tf.transpose(F)
# Print the values of matrices F and G
print("Matrix F:")
print(F.numpy())
print("\nMatrix G (Transpose of F):")
print(G.numpy())

Matrix F:
[[0.7740722  0.759274  ]
 [0.01919842 0.01035619]]

Matrix G (Transpose of F):
[[0.7740722  0.01919842]
 [0.759274   0.01035619]]


In [19]:
# Calculate the element-wise exponential of F and store the result in H
H = tf.math.exp(F)
# Print the values of matrices F and H
print("Matrix F:")
print(F.numpy())
print("\nMatrix H (Element-wise Exponential of F):")
print(H.numpy())

Matrix F:
[[0.7740722  0.759274  ]
 [0.01919842 0.01035619]]

Matrix H (Element-wise Exponential of F):
[[2.168579  2.1367245]
 [1.0193839 1.01041  ]]


In [20]:
# Calculate the transpose of F and store the result in G
G = tf.transpose(F)
# Concatenate F and G horizontally to create I
I = tf.concat([F, G], axis=1)  # Concatenate along columns (axis=1)
# Print the values of matrices F, G, and I
print("Matrix F:")
print(F.numpy())
print("\nMatrix G (Transpose of F):")
print(G.numpy())
print("\nMatrix I (F concatenated with G horizontally):")
print(I.numpy())

Matrix F:
[[0.7740722  0.759274  ]
 [0.01919842 0.01035619]]

Matrix G (Transpose of F):
[[0.7740722  0.01919842]
 [0.759274   0.01035619]]

Matrix I (F concatenated with G horizontally):
[[0.7740722  0.759274   0.7740722  0.01919842]
 [0.01919842 0.01035619 0.759274   0.01035619]]
